---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.model.name }}-models-pvc
  namespace: "{{ .Values.dataScienceProjectNamespace }}"
  labels:
    model: {{ .Values.model.name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi