apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-registry.fullname" . }}-db-parameters
  namespace: {{ .Values.registry.namespace }}
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: {{ .Values.registryDb.allowEmptyPassword
    | quote }}
  MYSQL_DATABASE: {{ .Values.registryDb.databaseName | quote }}
  MYSQL_PORT: {{ .Values.registryDb.databasePort | default 3306 | quote }}