apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  name: {{ include "model-registry.fullname" . }}
  namespace: {{ .Values.registry.namespace }}
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: {{ include "model-registry.fullname" . }}
spec:
  {{- with .Values.registry.grpc }}
  grpc:
    {{- if .image }}
    image: {{ .image }}
    {{- end }}
    {{- if .port }}
    port: {{ .port | default 9090 }}
    {{- end }}
    {{- with .resources }}
    resources:
      limits:
        cpu: {{ .limits.cpu | default "100m" }}
        memory: {{ .limits.memory | default "256Mi" }}
      requests:
        cpu: {{ .requests.cpu | default "100m" }}
        memory: {{ .requests.memory | default "256Mi" }}
    {{- end }}
  {{- end }}

  {{- with .Values.registry.rest }}
  rest:
    {{- if .image }}
    image: {{ .image }}
    {{- end }}
    {{- if .port }}
    port: {{ .port | default 8080 }}
    {{- end }}
    {{- with .resources }}
    resources:
      limits:
        cpu: {{ .limits.cpu | default "100m" }}
        memory: {{ .limits.memory | default "256Mi" }}
      requests:
        cpu: {{ .requests.cpu | default "100m" }}
        memory: {{ .requests.memory | default "256Mi" }}
    {{- end }}
    serviceRoute: {{ .serviceRoute }}
  {{- end }}
  
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled

  mysql:
    database: metadb
    host: {{ include "model-registry.fullname" . }}-db.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: {{ include "model-registry.fullname" . }}-db
    port: {{ .Values.registryDb.databasePort | default 3306 }}
    username: root
  