apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.fullname" . }}-db
  namespace: {{ .Values.registry.namespace }}
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: {{ required "registryDb.databaseName is required" .Values.registryDb.databaseName
    | b64enc | quote }}
  database-password: {{ required "registryDb.databasePassword is required" .Values.registryDb.databasePassword
    | b64enc | quote }}
  database-user: {{ required "registryDb.databaseUser is required" .Values.registryDb.databaseUser
    | b64enc | quote }}
type: Opaque