apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  name: {{ include "model-registry.fullname" . }}
  namespace: {{ .Values.registry.namespace }}
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: {{ include "model-registry.fullname" . }}
spec:
  grpc:
    image: {{ .Values.registry.grpc.image | default "registry.redhat.io/rhoai/odh-mlmd-grpc-server-rhel8:v2.17" }}
    port: {{ .Values.registry.grpc.port | default 9090 }}
    {{- with .Values.registry.grpc.resources }}
    resources:
      limits:
        cpu: {{ .limits.cpu | default "100m" }}
        memory: {{ .limits.memory | default "256Mi" }}
      requests:
        cpu: {{ .requests.cpu | default "100m" }}
        memory: {{ .requests.memory | default "256Mi" }}
    {{- end }}

  istio:
    audiences:
    - https://kubernetes.default.svc
    authConfigLabels:
      security.opendatahub.io/authorization-group: default
    authProvider: redhat-ods-applications-auth-provider
    gateway:
      grpc:
        gatewayRoute: enabled
        port: 443
        tls:
          credentialName: default-modelregistry-cert
          mode: SIMPLE
      istioIngress: ingressgateway
      rest:
        gatewayRoute: enabled
        port: 443
        tls:
          credentialName: default-modelregistry-cert
          mode: SIMPLE
    tlsMode: ISTIO_MUTUAL
  mysql:
    database: metadb
    host: {{ include "model-registry.fullname" . }}-db.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: {{ include "model-registry.fullname" . }}-db
    port: {{ .Values.registryDb.databasePort | default 3306 }}
    skipDBCreation: false
    username: root
  rest:
    image: {{ .Values.registry.rest.image | default "registry.redhat.io/rhoai/odh-mlmd-grpc-server-rhel8:v2.17" }}
    port: 8080
    {{- with .Values.registry.rest.resources }}
    resources:
      limits:
        cpu: {{ .limits.cpu | default "100m" }}
        memory: {{ .limits.memory | default "256Mi" }}
      requests:
        cpu: {{ .requests.cpu | default "100m" }}
        memory: {{ .requests.memory | default "256Mi" }}
    {{- end }}
    serviceRoute: disabled