apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "model-registry.fullname" . }}-metadata-mysql
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.metadataMysql.storageRequest | quote }}