apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.fullname" . }}-{{ .Values.registry.name }}-db-secrets
  namespace: {{ .Values.registry.namespace }}
  labels:
  {{- include "model-registry.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: {{ required "registryDb.databasePassword is required"
    .Values.registryDb.databasePassword | b64enc | quote }}
  MYSQL_USER_NAME: {{ required "registryDb.databaseUser is required" .Values.registryDb.databaseUser
    | b64enc | quote }}
type: Opaque