apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-registry.fullname" . }}-{{ .Values.registry.name }}-db
  namespace: {{ .Values.registry.namespace }}
  labels:
    component: db
  {{- include "model-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registryDb.type }}
  selector:
    component: db
    {{- include "model-registry.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.registryDb.ports | toYaml | nindent 2 }}