kubernetesClusterDomain: cluster.local

registry:
  name: users
  grpc:
    image: registry.redhat.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:927a88bade78e121d84e4d072f07a203fb00173af3615e00ce712d45329dde2d
    # port: 9090
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 256Mi
    #   requests:
    #     cpu: 100m
    #     memory: 256Mi

pvc:
  metadataMysql:
    storageRequest: 10Gi

registryDb:
  allowEmptyPassword: "true"
  dbContainer:
    args:
    - --datadir
    - /var/lib/mysql/datadir
    - --default-authentication-plugin=mysql_native_password
    image:
      repository: mysql
      tag: 8.0.3
    imagePullPolicy: IfNotPresent
  ports:
  - name: dbapi
    port: 3306
    protocol: TCP
    targetPort: 3306
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  type: ClusterIP

# registryDbParameters:
#   mysqlAllowEmptyPassword: "true"
#   mysqlDatabase: metadb
#   mysqlPort: "3306"
