kubernetesClusterDomain: cluster.local

registry:
  namespace: rhoai-model-registries
  grpc:
    image: registry.redhat.io/rhoai/odh-mlmd-grpc-server-rhel8@sha256:927a88bade78e121d84e4d072f07a203fb00173af3615e00ce712d45329dde2d
    # port: 9090
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 256Mi
    #   requests:
    #     cpu: 100m
    #     memory: 256Mi

pvc:
  metadataMysql:
    storageRequest: 10Gi

registryDb:
  allowEmptyPassword: "true"
  dbContainer:
    image:
      repository: mysql
      tag: 8.0.3
    imagePullPolicy: IfNotPresent
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  type: ClusterIP

# registryDbParameters:
#   mysqlAllowEmptyPassword: "true"
#   mysqlDatabase: metadb
#   mysqlPort: "3306"
